# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-09 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_auto_20180409_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
