# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-10 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0006_cart_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_user',
        ),
    ]
