# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-10 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import pay.models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0009_remove_cart_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='model',
            field=models.ForeignKey(default=True, on_delete=pay.models.Product, to='pay.UserProfile'),
        ),
    ]
