# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-11 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0011_auto_20180410_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_user',
            field=models.CharField(default=True, max_length=1000),
        ),
    ]
