# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-11 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0015_auto_20180411_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_pprice',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
