# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-11 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0016_auto_20180411_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.Product'),
        ),
    ]
