# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-11 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0018_auto_20180411_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
