# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-11 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0021_remove_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_product', models.CharField(max_length=300)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('order_status', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.UserProfile')),
            ],
        ),
    ]
