# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-11 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0022_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_status',
            new_name='order_payment_status',
        ),
    ]
