# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0023_auto_20180411_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cart',
            field=models.CharField(default='Not added', max_length=30),
            preserve_default=False,
        ),
    ]
