# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-14 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0024_order_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
