# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-14 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0026_order_order_txnid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_txnid',
            new_name='order_txn_id',
        ),
    ]
