# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0030_auto_20180415_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_pdf',
            field=models.FileField(default='', upload_to='pdf'),
            preserve_default=False,
        ),
    ]
