# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0031_order_order_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_pdf',
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
