# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0033_auto_20180417_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
