# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0036_auto_20180417_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_by',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
