# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0037_order_order_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='p_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
