# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0038_userprofile_p_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='p_image',
            new_name='image',
        ),
    ]
