# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0039_auto_20180424_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
