# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-05 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0042_auto_20180505_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_description',
            field=models.TextField(max_length=10000),
        ),
    ]
