# Generated by Django 2.0.5 on 2018-05-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0043_auto_20180505_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_pdescription',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_description',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
